{% set name = "edgetest" %}
{% set version = "2024.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a3461419b16e92aa48c1977ffe58b20e6c43c6c6194eed42e432640cf4be64e

build:
  noarch: python
  entry_points:
    - edgetest=edgetest.interface:cli
  number: 0
  script: {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - Cerberus <=1.3.5,>=1.3.0
    - click <=8.1.7,>=7.0
    - pluggy <=1.4.0,,>=1.0.0
    - tabulate <=0.9.0,>=0.8.9
    - packaging <=24.0,>20.6
    - tomlkit <=0.11.4,>=0.11.4
    - python >=3.8

test:
  imports:
    - edgetest

about:
  home: https://github.com/capitalone/edgetest
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: edgetest is a tox-inspired python library that tests your package against the latest available dependency versions.
  description: |
    edgetest is a tox-inspired python library that tests your package against the latest available dependency versions.
    It will create a virtual environment, install your local package into the environment, upgrade specified dependency
    package(s), and run your test command.
  doc_url: https://capitalone.github.io/edgetest/
  dev_url: https://github.com/capitalone/edgetest

extra:
  recipe-maintainers:
    - jdawang
    - gladysteh99
    - NikhilJArora
    - fdosani
    - ak-gupta
