{% set name = "edgetest" %}
{% set version = "2025.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6373d1f0553f25264ccd994a0ecadce51e0831f62d884d6acea7054fb878660e

build:
  noarch: python
  entry_points:
    - edgetest=edgetest.interface:cli
  number: 0
  script: {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64.0.0
  run:
    - Cerberus <=1.3.5,>=1.3.0
    - click <=8.1.7,>=7.0
    - pluggy <=1.5.0,>=1.0.0
    - tabulate <=0.9.0,>=0.8.9
    - packaging <=24.1,>20.6
    - tomlkit <=0.11.4,>=0.11.4
    - uv <=0.4.26,>=0.2.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - edgetest

about:
  home: https://github.com/capitalone/edgetest
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: edgetest is a tox-inspired python library that tests your package against the latest available dependency versions.
  description: |
    edgetest is a tox-inspired python library that tests your package against the latest available dependency versions.
    It will create a virtual environment, install your local package into the environment, upgrade specified dependency
    package(s), and run your test command.
  doc_url: https://capitalone.github.io/edgetest/
  dev_url: https://github.com/capitalone/edgetest

extra:
  recipe-maintainers:
    - jdawang
    - gladysteh99
    - NikhilJArora
    - fdosani
    - ak-gupta
